import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
// import { fetchCount } from './counterAPI';

export interface FlightsState {
    value: number;
    status: 'idle' | 'loading' | 'failed';
}

const initialState: FlightsState = {
    value: 0,
    status: 'idle',
  };

  export const flightsSlice = createSlice({
    name: 'flights',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: () => {
      
    },
  });
  
  export default flightsSlice.reducer;