import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import {fetchAllFlights} from '../../api/client';
// import { fetchCount } from './counterAPI';

// export const fetchPosts = createAsyncThunk('flight/fetchFlight', async () => {
//   const response = await client.get('fakeApi/posts')
//   return response.flight
// })
const dummyData:IFlight[] = [
  {id: 1,number: "LX1498", to: "ZRH", from: "PRG", aircraft: "", date:"09.04.2020", duration:80},
  {id: 2,number: "LX2098", to: "PRG", from: "ZRH", aircraft: "", date:"13.04.2020", duration:95}
]

export interface IFlight {
  id: number,
  number?: string,
  to?: string,
  from?: string,
  aircraft?: string,
  date?:string,
  duration?:number
}

export interface FlightsState {
    flights: IFlight[];
    loading: Boolean;
    hasErrors: Boolean;
};

const initialState: FlightsState = {
    flights: dummyData,
    loading: false,
    hasErrors: false
  };

export const flightsSlice = createSlice({
  name: 'flights',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    getFlights: state => {
      state.loading = true
    },
    getFlightsSuccess: (state, {payload}) => {
      state.flights = payload
      state.loading = false
      state.hasErrors = false
    },
    getFlightsFailure: state => {
      state.loading = false
      state.hasErrors = false
    }
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    
  },
});
  
export const {getFlights, getFlightsSuccess, getFlightsFailure} = flightsSlice.actions
export const flightsSelector = (state:RootState) => state.flights

export default flightsSlice.reducer;

export const fetchFlights = createAsyncThunk('flights/fetchFlights', async () => {
  const response = await fetchAllFlights()
  // return response.flights  
})
  